Artist.create([
  {email: "rusted@root.com",
    password: "password",
    password_confirmation: "password",
    name: "Rusted Root",
    image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/rustedroot.jpg",
    description: "Rusted Root is an American band from Pittsburgh, Pennsylvania known for their fusion of acoustic, rock, world and other styles of music, with a strong percussion section that draws from African, Latin American, and Native American influences. Their lyrical content varies but often talks about Christianity and Judaism. Rusted Root has sold more than three million albums worldwide.\r\n\r\nThe band achieved fame in 1994 with its platinum-selling album When I Woke, which included hit single \"Send Me On My Way.\" The song has been featured prominently in many films and commercials.",
    album1title: "When I Woke",
    album1image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/rustedroot1.jpg",
    album1itunes:"https://itunes.apple.com/us/album/when-i-woke/id120303",
    album2title: "Rusted Root Live",
    album2image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/rustedroot2.jpg",
    album2itunes:"https://itunes.apple.com/us/album/rusted-root-live/id38501658",
    album3title: "20th Century Masters - The Millennium Collection: The Best of Rusted Root",
    album3image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/rustedroot3.jpg",
    album3itunes:"https://itunes.apple.com/us/album/20th-century-masters-millennium/id56509832",
    album4title: "Rusted Root",
    album4image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/rustedroot4.jpg",
    album4itunes:"https://itunes.apple.com/us/album/rusted-root/id386063",
   },
  {email: "prince@prince.com",
    password: "password",
    password_confirmation: "password",
    name: "prince",
    image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/prince.jpg",
    description: "Prince Rogers Nelson (born June 7, 1958), known by his mononym Prince, is an American singer, songwriter, multi-instrumentalist and actor and has been a major figure in popular music for over three decades. Prince is renowned as an innovator and is widely known for his eclectic work, flamboyant stage presence, and wide vocal range. He is widely regarded as the pioneer of Minneapolis sound. His music combines rock, R&B, soul, funk, hip hop, disco, psychedelia, jazz, and pop.",
    album1title: "The Very Best of Prince",
    album1image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/prince1.jpg",
    album1itunes:"https://itunes.apple.com/us/album/the-very-best-of-prince/id175020481
",
    album2title: "Purple Rain (Soundtrack from the Motion Picture)",
    album2image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/prince2.jpg",
    album2itunes:"https://itunes.apple.com/us/album/purple-rain-soundtrack-from/id214145442",
    album3title: "The Hits / The B-Sides",
    album3image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/prince3.jpg",
    album3itunes:"https://itunes.apple.com/us/album/the-hits-the-b-sides/id212972881",
    album4title: "Art Official Age",
    album4image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/prince4.jpg",
    album4itunes:"https://itunes.apple.com/us/album/art-official-age/id911631220",
  },
  {email: "adele@gmail.com",
    password: "password",
    password_confirmation: "password",
    name: "Adele",
    image_url: "https://lh3.googleusercontent.com/-btyoRiX1qEA/VijxPETIslI/AAAAAAAAAts/TiZBFDP4mjc/w2048-h2048/Adele_25_Cover_4000_141015.jpg",
    description: "Adele Laurie Blue Adkins MBE (/əˈdɛl/; born 5 May 1988) is an English singer and songwriter. Graduating from the BRIT School for Performing Arts and Technology in 2006, Adele was given a recording contract by XL Recordings after a friend posted her demo on Myspace the same year. In 2007, she received the Brit Awards \"Critics' Choice\" award and won the BBC Sound of 2008 poll. Her debut album, 19, was released in 2008 to commercial and critical success. It is certified seven times platinum in the UK, and double platinum in the US. An appearance she made on Saturday Night Live in late 2008 boosted her career in the US. At the 51st Annual Grammy Awards in 2009, Adele received the awards for Best New Artist and Best Female Pop Vocal Performance.",
    album1title: "25",
    album1image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/adele1.jpg",
    album1itunes:"https://itunes.apple.com/us/album/25/id1051394208",
    album2title: "21",
    album2image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/adele2.jpg",
    album2itunes:"https://itunes.apple.com/us/album/21/id420075073",
    album3title: "19",
    album3image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/adele3.jpg",
    album3itunes:"https://itunes.apple.com/us/album/19/id282374043",
    album4title: "iTunes Live From SoHo",
    album4image: "https://dl.dropboxusercontent.com/u/1515/fanluv/albums/adele4.jpg",
    album4itunes:"https://itunes.apple.com/us/album/itunes-live-from-soho/id303197123",
  },
  {email: "madonna@gmail.com",
    password: "password",
    password_confirmation: "password",
    name: "Madonna",
    image_url: "http://www.madonnarama.com/artworks/posts/20140516-pictures-madonna-uomo-vogue-tom-munro-spread-hq-06.jpg",
    description: "Madonna Louise Ciccone (/tʃɪˈkoʊni/; Italian: [tʃikˈkoːne]) (born August 16, 1958) is an American singer, songwriter, actress, and businesswoman. She achieved popularity by pushing the boundaries of lyrical content in mainstream popular music and imagery in her music videos, which became a fixture on MTV. Madonna is known for reinventing both her music and image, and for maintaining her autonomy within the recording industry. Music critics have acclaimed her musical productions, which have generated some controversy. Often referred to as the \"Queen of Pop\", she is cited as an influence by numerous other artists around the world.",
    album1title: "The Immaculate Collection",
    album1image: "",
    album1itunes:"https://itunes.apple.com/us/album/the-immaculate-collection/id80812428",
    album2title: "Rebel Heart",
    album2image: "",
    album2itunes:"https://itunes.apple.com/us/album/rebel-heart-deluxe/id953710965",
    album3title: "Hardy Candy",
    album3image: "",
    album3itunes:"https://itunes.apple.com/us/album/hard-candy-deluxe-version/id278674439",
    album4title: "Confessions on a Dance Floor",
    album4image: "",
    album4itunes:"https://itunes.apple.com/us/album/confessions-on-a-dance-floor/id91992239",
  },
  {email: "pearl@jam.com",
    password: "password",
    password_confirmation: "password",
    name: "Pearl Jam",
    image_url: "https://consequenceofsound.files.wordpress.com/2014/04/pearl-jam-e1396906130680.jpg",
    description: "Pearl Jam is an American rock band, formed in Seattle, Washington, in 1990. Since its inception, the band's line-up has comprised Eddie Vedder (lead vocals), Mike McCready (lead guitar), Stone Gossard (rhythm guitar) and Jeff Ament (bass). The band's fifth member is drummer Matt Cameron (also of Soundgarden), who has been with the band since 1998. Boom Gaspar (piano) has also been a session/touring member with the band since 2002. Drummers Dave Krusen, Matt Chamberlain, Dave Abbruzzese and Jack Irons are former members of the band.",
    album1title: "Lightning Bolt",
    album1image: "",
    album1itunes:"https://itunes.apple.com/us/album/lightning-bolt/id665391109",
    album2title: "Rearviewmirror: Greatest Hits 1991-2003",
    album2image: "",
    album2itunes:"https://itunes.apple.com/us/album/rearviewmirror-greatest-hits/id158049800",
    album3title: "Ten",
    album3image: "",
    album3itunes:"https://itunes.apple.com/us/album/ten/id425465247",
    album4title: "Pearl Jam",
    album4image: "",
    album4itunes:"https://itunes.apple.com/us/album/pearl-jam/id220206594",
  },
  {email: "radio@head.com",
    password: "password",
    password_confirmation: "password",
    name: "Radiohead",
    image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/radiohead.jpg",
    description: "Radiohead are an English rock band from Abingdon, Oxfordshire, formed in 1985. The band consists of Thom Yorke (lead vocals, guitar, piano), Jonny Greenwood (lead guitar, keyboards, other instruments), Colin Greenwood (bass), Phil Selway (drums, percussion, backing vocals) and Ed O'Brien (guitar, backing vocals).",
    album1title: "In Rainbows",
    album1image: "",
    album1itunes:"https://itunes.apple.com/us/album/in-rainbows/id270079778",
    album2title: "The King of Limbs",
    album2image: "",
    album2itunes:"https://itunes.apple.com/us/album/the-king-of-limbs/id425806837",
    album3title: "The Best of Radiohead",
    album3image: "",
    album3itunes:"https://itunes.apple.com/us/album/the-best-of-radiohead/id732055461",
    album4title: "Kid A",
    album4image: "",
    album4itunes:"https://itunes.apple.com/us/album/ok-computer/id696736813",
  },
  {email: "chelsea@wolfe.com",
    password: "password",
    password_confirmation: "password",
    name: "Chelsea Wolfe",
    image_url: "https://f1.bcbits.com/img/a1674916295_10.jpg",
    description: "Chelsea Joy Wolfe (born November 14, 1983) is an American singer-songwriter, based in Los Angeles, California, United States.[1] Her mix of styles, including gothic, folk, electronic, metal[2][3] and neofolk,[4] has been described as \"drone-metal-art-folk\",[5] and is characterized by experimental guitar playing, hazy vocals and surreal soundscapes.",
    album1title: "Abyss",
    album1image: "",
    album1itunes:"https://itunes.apple.com/us/album/abyss/id988559297",
    album2title: "Pain Is Beauty",
    album2image: "",
    album2itunes:"https://itunes.apple.com/us/album/pain-is-beauty/id681692672",
    album3title: "Unknown Rooms: A Collection of Acoustic Songs",
    album3image: "",
    album3itunes:"https://itunes.apple.com/us/album/unknown-rooms-collection-acoustic/id556842028",
    album4title: "Apokalypsis",
    album4image: "",
    album4itunes:"https://itunes.apple.com/us/album/apokalypsis/id858997507",
  },
  {email: "dillinger@escape.com",
    password: "password",
    password_confirmation: "password",
    name: "The Dillinger Escape Plan",
    image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/dillinger.jpg",
    description: "The Dillinger Escape Plan is an American mathcore band from Morris Plains, New Jersey. The group originated in 1997 after the disbanding of Arcane, a hardcore punk trio consisting of Ben Weinman, Dimitri Minakakis, and Chris Pennie.[1] The band's current line-up consists of guitarists Ben Weinman and Kevin Antreassian, bassist Liam Wilson, vocalist Greg Puciato, and drummer Billy Rymer. Their band name is derived from bank robber John Dillinger.[2]",
    album1title: "One Of Us Is the Killer",
    album1image: "",
    album1itunes:"https://itunes.apple.com/us/album/one-of-us-is-the-killer/id632948195",
    album2title: "Ire Works",
    album2image: "",
    album2itunes:"https://itunes.apple.com/us/album/ire-works/id265229827",
    album3title: "Miss Machine",
    album3image: "",
    album3itunes:"https://itunes.apple.com/us/album/miss-machine/id65885064",
    album4title: "Calculating Infinity",
    album4image: "",
    album4itunes:"https://itunes.apple.com/us/album/calculating-infinity/id67965140",
  },
  {email: "bjork@gmail.com",
    password: "password",
    password_confirmation: "password",
    name: "Bjork",
    image_url: "http://www.interviewmagazine.com/files/2009/05/21/img-bjork-fig-1_110739349400.jpg",
    description: "Björk Guðmundsdóttir (Icelandic pronunciation: [ˈpjœr̥k ˈkvʏðmʏntsˌtouhtɪr], born 21 November 1965), known mononymously as Björk (/ˈbjɜːrk/), is an Icelandic singer-songwriter, multi-instrumentalist, and occasional actress. She initially became known as the lead singer of the alternative rock band The Sugarcubes, whose 1987 single \"Birthday\" was a hit on US and UK indie stations and a favorite among music critics. Björk embarked on a solo career in 1993, coming to prominence as a solo artist with her single \"Human Behaviour\" and her album Debut. She has since had 30 singles reach the Top 40 on pop charts around the world, with 22 Top 40 hits in the UK, including the Top 10 hits \"It's Oh So Quiet\", \"Army of Me\", and \"Hyperballad\". Additionally, \"Big Time Sensuality\", \"Hyperballad\" and \"I Miss You\" were number one Dance Hits in the US. Over her three-decade career, she has developed an experimental and eclectic musical style that draws on a wide range of influences and genres spanning electronica, jazz, rock, and the avant-garde. Critics have consistently praised Björk's work, praising her innovative approach to singing and composition, her musical experimentation, her music videos, and her distinctive voice; she has been described as \"the most important and forward-looking musician of her generation\" and \"the best non-pop female vocalist of the last 30 years.\"",
    album1title: "Vulnicura",
    album1image: "",
    album1itunes:"https://itunes.apple.com/us/album/vulnicura/id960042103",
    album2title: "Volta",
    album2image: "",
    album2itunes:"https://itunes.apple.com/us/album/volta/id252738426",
    album3title: "Medulla",
    album3image: "",
    album3itunes:"https://itunes.apple.com/us/album/medulla/id21393649",
    album4title: "Bjork's Greatest Hits",
    album4image: "",
    album4itunes:"https://itunes.apple.com/us/album/bjorks-greatest-hits/id262483556",
  },
  {email: "sam@smith.com",
    password: "password",
    password_confirmation: "password",
    name: "Sam Smith",
    image_url: "http://images.latinpost.com/data/images/full/34897/sam-smith-hot-new-music-2015.jpeg",
    description: "Samuel Frederick \"Sam\" Smith (born 19 May 1992) is an English singer-songwriter. He rose to fame in October 2012 when he was featured on Disclosure's breakthrough single \"Latch\", which peaked at number eleven on the UK Singles Chart. His subsequent feature—on Naughty Boy's \"La La La\"—earned him his first number one single in May 2013.\r\n\r\nIn December 2013, he was nominated for the 2014 Brit Critics' Choice Award and the BBC's Sound of 2014 poll, both of which he won. He released his debut studio album, In the Lonely Hour, in May 2014 on Capitol Records UK. The lead single, \"Lay Me Down\", was released prior to \"La La La\". The second single, \"Money on My Mind\", became his second number one single in the UK. The album's third single, \"Stay with Me\", was an international success, reaching number one in the UK and number two on the U.S. Billboard Hot 100, while the fourth single \"I'm Not the Only One\" reached the top five in both countries. The fifth single, \"Like I Can\", reached number nine in the UK.\r\n",
    album1title: "",
    album1image: "",
    album1itunes:"",
    album2title: "",
    album2image: "",
    album2itunes:"",
    album3title: "",
    album3image: "",
    album3itunes:"",
    album4title: "",
    album4image: "",
    album4itunes:"",
  },
  {email: "lady@gaga.com",
    password: "password",
    password_confirmation: "password",
    name: "Lady Gaga",
    image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/gaga.jpg", description: "Stefani Joanne Angelina Germanotta (/ˈstɛfəniː dʒɜːrməˈnɒtə/ stef-ə-nee jur-mə-not-ə; born March 28, 1986), known professionally as Lady Gaga, is an American singer, songwriter, and actress. She is known for her self-empowering messages, fashion, and live performances. Gaga initially performed in theater, appearing in high school plays, and studied at CAP21 through New York University's Tisch School of the Arts before dropping out to pursue a musical career. After leaving a rock band, participating in the Lower East Side's avant garde performance art circuit, and being dropped from a contract with Def Jam Recordings, Gaga worked as a songwriter for Sony/ATV Music Publishing. There, recording artist Akon noticed her vocal abilities and helped her to sign a joint deal with Interscope Records and his own KonLive Distribution.",
    album1title: "",
    album1image: "",
    album1itunes:"",
    album2title: "",
    album2image: "",
    album2itunes:"",
    album3title: "",
    album3image: "",
    album3itunes:"",
    album4title: "",
    album4image: "",
    album4itunes:"",
  },
  {email: "modest@mouse.com",
    password: "password",
    password_confirmation: "password",
    name: "Modest Mouse",
    image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/modestmouse.jpg",
    description: "Modest Mouse is an American rock band formed in 1992 in Issaquah, Washington and currently based in Portland, Oregon. The founding members of this group are lead singer/guitarist Isaac Brock, drummer Jeremiah Green, and bassist Eric Judy. Strongly influenced by groups such as Pavement, the Pixies, XTC, and Talking Heads, the band rehearsed, rearranged, and recorded demos for almost two years before finally signing with small-town indie label, K Records, and releasing numerous singles.[1] Since the band's 1996 debut album, This Is a Long Drive for Someone with Nothing to Think About, the group's lineup has centered on Brock and Green. Judy performed on every Modest Mouse album until his departure in 2012. Guitarist Johnny Marr (formerly of the Smiths) joined the band in 2006, shortly following percussionist Joe Plummer (formerly of the Black Heart Procession) and multi-instrumentalist Tom Peloso, to work on the album We Were Dead Before the Ship Even Sank. Guitarist Jim Fairchild joined the band in 2009. The band's sixth album, Strangers to Ourselves, was released on March 17, 2015.",
    album1title: "",
    album1image: "",
    album1itunes:"",
    album2title: "",
    album2image: "",
    album2itunes:"",
    album3title: "",
    album3image: "",
    album3itunes:"",
    album4title: "",
    album4image: "",
    album4itunes:"",
  },
  {email: "rihanna@gmail.com",
    password: "password",
    password_confirmation: "password",
    name: "rihanna",
    image_url: "http://a2.files.biography.com/image/upload/c_fit,cs_srgb,dpr_1.0,h_1200,q_80,w_1200/MTE1ODA0OTcxMzkwNjk5MDIx.jpg",
    description: "Robyn Rihanna Fenty (/riˈænə/ ree-an-ə),[2] (born February 20, 1988) is a Barbadian singer and songwriter. Born in Saint Michael and raised in Bridgetown, she first entered the music industry by recording demo tapes under the direction of record producer Evan Rogers in 2003. She ultimately signed a recording contract with Def Jam Recordings after auditioning for its then-president, hip-hop producer and rapper Jay Z. Rihanna's first two studio albums Music of the Sun (2005) and A Girl Like Me (2006) charted on the top 10 of the U.S. Billboard 200 and respectively produced the singles \"Pon de Replay\" and \"SOS\".",
    album1title: "",
    album1image: "",
    album1itunes:"",
    album2title: "",
    album2image: "",
    album2itunes:"",
    album3title: "",
    album3image: "",
    album3itunes:"",
    album4title: "",
    album4image: "",
    album4itunes:"",
  },
  {email: "tv@ontheradio.com",
    password: "test1234",
    password_confirmation: "test1234",
    name: "TV On The Radio",
    image_url: "http://static.stereogum.com/uploads/2011/02/tv-on-the-radio-608x572.jpg",
    description: "TV on the Radio are an American indie rock band formed in 2001 in Brooklyn, New York. The group has released several EPs including their debut Young Liars (2003), and five studio albums: Desperate Youth, Blood Thirsty Babes (2004), Return to Cookie Mountain (2006), Dear Science (2008), Nine Types of Light (2011), and Seeds (2014). For most of the band's existence, the core TV on the Radio lineup has been Tunde Adebimpe (vocals/loops), David Andrew Sitek (guitars/keyboards/loops), Kyp Malone (vocals/guitars/bass/loops) and Jaleel Bunton (drums/vocals/loops/guitars) as official members. Gerard Smith (bass/keyboards) was with the band from 2005 until his death in 2011. Other contributors have included David Bowie, Nick Zinner of Yeah Yeah Yeahs, Trent Reznor of Nine Inch Nails, Kazu Makino of Blonde Redhead, Martin Perna of Antibalas, and Katrina Ford of Celebration.",
    album1title: "",
    album1image: "",
    album1itunes:"",
    album2title: "",
    album2image: "",
    album2itunes:"",
    album3title: "",
    album3image: "",
    album3itunes:"",
    album4title: "",
    album4image: "",
    album4itunes:"",
  },
  {email: "elten@eleven.com",
    password: "password",
    password_confirmation: "password",
    name: "el ten eleven",
    image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/el-ten-eleven.jpg",
    description: "El Ten Eleven is a Los Angeles post-rock duo known for combining guitar/bass doubleneck or fretless bass, with heavy looping, or vamping, and the utility of an effects pedal, over acoustic or electric drumming. They have released six full-length albums, an ep and a remix album, earning generally positive reviews.\r\n\r\nThe band has earned some attention due to many of their songs being featured in the soundtracks of Gary Hustwit's design documentaries Helvetica, Objectified, and Urbanized.\r\n\r\nThe name El Ten Eleven is derived from the name of an airliner, the Lockheed L-1011 TriStar.",
    album1title: "",
    album1image: "",
    album1itunes:"",
    album2title: "",
    album2image: "",
    album2itunes:"",
    album3title: "",
    album3image: "",
    album3itunes:"",
    album4title: "",
    album4image: "",
    album4itunes:"",
  },
  {email: "pixies@gmail.com",
    password: "password",
    password_confirmation: "password",
    name: "Pixies",
    image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/pixies.jpg",
    description: "The Pixies are an American alternative rock band formed in 1986 in Boston, Massachusetts. The group disbanded in 1993 in acrimonious circumstances, but reunited in 2004. The group currently consists of founders Black Francis (lead vocals, rhythm guitar), Joey Santiago (lead guitar), and David Lovering (drums). Co-founder Kim Deal (bass, backing vocals) left in 2013 and was replaced by Kim Shattuck as live bass player for a few months, then by Paz Lenchantin for the band's 2014 tour. The Pixies achieved relatively modest popularity in their home country, but were significantly more successful in the United Kingdom, mainland Europe and Israel. The group is credited with having an influence on the alternative rock boom of the 1990s.",
    album1title: "",
    album1image: "",
    album1itunes:"",
    album2title: "",
    album2image: "",
    album2itunes:"",
    album3title: "",
    album3image: "",
    album3itunes:"",
    album4title: "",
    album4image: "",
    album4itunes:"",
  }
])
