Artist.create!([
  {email: "sam@smith.com", password_digest: "$2a$10$b5G3v8wNffr.ZgvitxN.he65uq1sJo5eFciokNPFzfI1ErmL3ChTW", name: "Sam Smith", image_url: "http://images.latinpost.com/data/images/full/34897/sam-smith-hot-new-music-2015.jpeg", description: nil},
  {email: "madonna@gmail.com", password_digest: "$2a$10$/xmZr/45wj2TpgG3Cplpxu2gMRdpKUIeOjyjTMtTCyHGqLgx3M4aO", name: "Madonna", image_url: "http://www.madonnarama.com/artworks/posts/20140516-pictures-madonna-uomo-vogue-tom-munro-spread-hq-06.jpg", description: nil},
  {email: "rihanna@gmail.com", password_digest: "$2a$10$NreK0cVrHaeEJusEGv4egeMyYZY1fCeru.3HPMS3Per28MIiXaXVe", name: "rihanna", image_url: "http://a2.files.biography.com/image/upload/c_fit,cs_srgb,dpr_1.0,h_1200,q_80,w_1200/MTE1ODA0OTcxMzkwNjk5MDIx.jpg", description: nil},
  {email: "adele@gmail.com", password_digest: "$2a$10$Eb5h3m5FkN30VbTpR.qJPe/y5jRS4Q.80CM5q.NmjtPrsRfYKXTPO", name: "Adele", image_url: "https://lh3.googleusercontent.com/-btyoRiX1qEA/VijxPETIslI/AAAAAAAAAts/TiZBFDP4mjc/w2048-h2048/Adele_25_Cover_4000_141015.jpg", description: nil},
  {email: "rusted@root.com", password_digest: "$2a$10$qGU0dXdb0x9RN.U8VBvcMukuh8lQvoTZhHQm3Hbr0CuJRON0d.TUa", name: "Rusted Root", image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/rustedroot.jpg", description: nil},
  {email: "lady@gaga.com", password_digest: "$2a$10$82neLUmD1gIsax9hoHEmHOqBbrErSoqpRxQdEy1je.yF1B0i6nM9S", name: "Lady Gaga", image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/gaga.jpg", description: nil},
  {email: "whitney@houston.com", password_digest: "$2a$10$l9MJjO8v8rRkxAX4ZP62UODWP8aa6HH8WxppgSCho7Hdtl4CVGGBW", name: "Whitney Houston", image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/whitney.jpg", description: nil},
  {email: "prince@prince.com", password_digest: "$2a$10$SQaGklDmhujBeYGQO0ALLOQkB4IBQEei.McpO7H.QsT6YzQraaImu", name: "prince", image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/prince.jpg", description: nil},
  {email: "pearl@jam.com", password_digest: "$2a$10$Dbzn.IT51lSTht.J/FeyMeVQD0zN2B1Ih8DxhNEOgR9LYNrf6Jf4O", name: "Pearl Jam", image_url: "https://consequenceofsound.files.wordpress.com/2014/04/pearl-jam-e1396906130680.jpg", description: "Pearl Jam is an American rock band, formed in Seattle, Washington, in 1990. Since its inception, the band's line-up has comprised Eddie Vedder (lead vocals), Mike McCready (lead guitar), Stone Gossard (rhythm guitar) and Jeff Ament (bass). The band's fifth member is drummer Matt Cameron (also of Soundgarden), who has been with the band since 1998. Boom Gaspar (piano) has also been a session/touring member with the band since 2002. Drummers Dave Krusen, Matt Chamberlain, Dave Abbruzzese and Jack Irons are former members of the band."},
  {email: "radio@head.com", password_digest: "$2a$10$W81oI99iyjdCqenTIZhJOect1RIjbb6LuZXttJwFCPLfFAQImy.Ne", name: "Radiohead", image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/radiohead.jpg", description: "Radiohead are an English rock band from Abingdon, Oxfordshire, formed in 1985. The band consists of Thom Yorke (lead vocals, guitar, piano), Jonny Greenwood (lead guitar, keyboards, other instruments), Colin Greenwood (bass), Phil Selway (drums, percussion, backing vocals) and Ed O'Brien (guitar, backing vocals)."},
  {email: "chelsea@wolfe.com", password_digest: "$2a$10$K0kl1vU2oyLa8QVjmiEd1O9bIKu053f1U1rA1NJGDtHy/D4ZruVtG", name: "Chelsea Wolfe", image_url: "https://f1.bcbits.com/img/a1674916295_10.jpg", description: "Chelsea Joy Wolfe (born November 14, 1983) is an American singer-songwriter, based in Los Angeles, California, United States.[1] Her mix of styles, including gothic, folk, electronic, metal[2][3] and neofolk,[4] has been described as \"drone-metal-art-folk\",[5] and is characterized by experimental guitar playing, hazy vocals and surreal soundscapes."},
  {email: "dillinger@escape.com", password_digest: "$2a$10$F5tS/TJJoJi19746YP127ethLtDcRreWj0mHc7JdF9beR7IDLDgge", name: "The Dillinger Escape Plan", image_url: "https://dl.dropboxusercontent.com/u/1515/fanluv/artist%20images/dillinger.jpg", description: "The Dillinger Escape Plan is an American mathcore band from Morris Plains, New Jersey. The group originated in 1997 after the disbanding of Arcane, a hardcore punk trio consisting of Ben Weinman, Dimitri Minakakis, and Chris Pennie.[1] The band's current line-up consists of guitarists Ben Weinman and Kevin Antreassian, bassist Liam Wilson, vocalist Greg Puciato, and drummer Billy Rymer. Their band name is derived from bank robber John Dillinger.[2]"},
  {email: "bjork@gmail.com", password_digest: "$2a$10$gCWmeCOn1Pl7qBJLuqvw6eDbncafL1mxROKqju2.gVGaGJRzy2ZQW", name: "Bjork", image_url: "http://www.interviewmagazine.com/files/2009/05/21/img-bjork-fig-1_110739349400.jpg", description: "Björk Guðmundsdóttir (Icelandic pronunciation: [ˈpjœr̥k ˈkvʏðmʏntsˌtouhtɪr], born 21 November 1965), known mononymously as Björk (/ˈbjɜːrk/), is an Icelandic singer-songwriter, multi-instrumentalist, and occasional actress. She initially became known as the lead singer of the alternative rock band The Sugarcubes, whose 1987 single \"Birthday\" was a hit on US and UK indie stations and a favorite among music critics. Björk embarked on a solo career in 1993, coming to prominence as a solo artist with her single \"Human Behaviour\" and her album Debut. She has since had 30 singles reach the Top 40 on pop charts around the world, with 22 Top 40 hits in the UK, including the Top 10 hits \"It's Oh So Quiet\", \"Army of Me\", and \"Hyperballad\". Additionally, \"Big Time Sensuality\", \"Hyperballad\" and \"I Miss You\" were number one Dance Hits in the US. Over her three-decade career, she has developed an experimental and eclectic musical style that draws on a wide range of influences and genres spanning electronica, jazz, rock, and the avant-garde. Critics have consistently praised Björk's work, praising her innovative approach to singing and composition, her musical experimentation, her music videos, and her distinctive voice; she has been described as \"the most important and forward-looking musician of her generation\" and \"the best non-pop female vocalist of the last 30 years.\""}
])
Fan.create!([
  {email: "rusted@root.com", password_digest: "$2a$10$XoMolwf7ZugdUY0kCUIkt.bjG11Qdy1Hmea5P5N0uu4B379fOmECu", name: "Rusted Root", image_url: nil},
  {email: "rihanna@gmail.com", password_digest: "$2a$10$rbC6HQvAtXvsQdAkU0D9cOC.BVYE8hPI45A1ZzcleQX2BnS08Rana", name: "Rihanna", image_url: nil},
  {email: "adele@gmail.com", password_digest: "$2a$10$FJpJZdvD.W8uX07EyOH1ROisEWUVTOzAhbtvFnzLYuPJzQ6Wh7.Ya", name: "Adele", image_url: "https://lh3.googleusercontent.com/-btyoRiX1qEA/VijxPETIslI/AAAAAAAAAts/TiZBFDP4mjc/w2048-h2048/Adele_25_Cover_4000_141015.jpg"},
  {email: "dknutson@gmail.com", password_digest: "$2a$10$4mvlgiQjkPtIYjGA9x4jL.ht0UeRpD1IMM94XOODpxVCO5Sr8FMma", name: "Dan", image_url: "https://scontent-mia1-1.xx.fbcdn.net/hphotos-xaf1/v/t1.0-9/10653302_10153323978886056_7089087466929341850_n.jpg?oh=8118db9c475de61c25a6b674beb43f07&oe=578C9FE0"}
])
Luv.create!([
  {artist_id: 1, fan_id: 1},
  {artist_id: 3, fan_id: 1}
])
